Use github actions (Fix #1)
neelkamath/brians-brain pull request #2
Opened 2020-10-04 17:55 UTC by AshtrayShetty

2020-10-05 00:52 UTC, neelkamath requested changes

2020-10-05 00:52 UTC, neelkamath commented on .github/workflows/workflow.yml
> +      - uses: actions/upload-artifact@v2
We want this step to always run. Currently, if the tests fail, this step will be skipped. See [this snippet](https://github.com/neelkamath/omni-chat/blob/master/.github/workflows/workflow.yml#L42) for a hint.

2020-10-05 16:37 UTC, AshtrayShetty commented
Hey! I made some changes. Will this suffice?

2020-10-06 01:34 UTC, neelkamath approved these changes

2020-10-06 01:34 UTC, merged